### ISSUE TITLE
Transaction Validation

### ISSUE THREAD

**Issue by barnjamin** [algorand/pyteal-utils#2]
Some set of functions to do basic checks on all the transactions in a group would be nice.

`no_rekey`: Check that none of the transactions in the group are rekeys
`no_close_to`: Check that none of the transactions in the group have a closeTo set

**Comment by cusma** [comment]
`no_close_asset_to`: Check that none of the AssetTransfer transactions in the group have a assetCloseTo set

**Comment by barnjamin** [comment]
merged
