### ISSUE TITLE
Signed integers

### ISSUE THREAD

**Issue by CiottiGiorgio** [algorand/pyteal-utils#8]
It would be nice to have signed integers implemented on top of unsigned integers with two's complement.
Then we could still use native unsigned addition for both addition and subtraction among signed integers.
I think multiplication can still use the native unsigned instruction. Not sure about division (i think it's basically just repeated subtraction).

They would have to be in line with `uint64` and throw an error in case of overflow/underflow.

**Comment by CiottiGiorgio** [comment]
Initial attempt at the skeleton of the PR.

https://github.com/CiottiGiorgio/pyteal-utils/tree/fixed_point

**Comment by barnjamin** [comment]
merged
